2차원 리스트

<img src="./2DIM.png" align="left" width="1500" title="2차원 리스트">

In [1]:
a = [[1, 2, 3], [4, 5, 6]]
print(type(a))
print(a)

<class 'list'>
[[1, 2, 3], [4, 5, 6]]


In [2]:
import numpy as np
b = np.array(a)
print(type(b))
print(b)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [3]:
a = [0] * 5
print(a)
b = [0 for _ in range(5)]
print(b)

[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]


In [4]:
# 리스트이름 = [[초기값] * 열개수 for 변수 in range(행개수)]
a = [[0] * 5 for i in range(4)]
print(a)
b = np.array(a)
print(b)

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [5]:
print(len(a)) # 행의 개수
print(len(a[0])) # 열의 개수
# print(a.shape) # 파이썬의 list는 shape라는 속성이 없으므로 에러가 발생된다.
print(len(b))
print(len(b[0]))
print(b.shape) # 넘파이는 shape 속성을 이용해서 배열의 크기를 튜플로 얻어온다.
print(b.shape[0])
print(b.shape[1])

4
5
4
5
(4, 5)
4
5


In [6]:
for i in range(len(a)):
    print(a[i])

[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]


In [7]:
for i in range(len(a)):
    for j in range(len(a[i])):
        print(a[i][j], end=' ')
    print()

0 0 0 0 0 
0 0 0 0 0 
0 0 0 0 0 
0 0 0 0 0 


<img src="./2DIM2.png" align="left" width="400" title="2차원 리스트">

In [8]:
# 2차원 리스트의 데이터를 출력하는 함수
def pprint(data):
    for i in range(len(data)):
        for j in range(len(data[i])):
            print('{:3d}'.format(data[i][j]), end=' ')
        print()

In [9]:
# 2차원 리스트를 만들려는 행과 열의 개수를 입력받아 2차원 리스트를 만든다.
row, col = map(int, input('2차원 리스트를 만들려는 행과 열의 개수: ').split())
data = [[0] * col for _ in range(row)]
n = 0 # 리스트에 1씩 증가하며 채워질 숫자가 기억되는 변수

# 짝수행은 숫자가 왼쪽에서 오른쪽으로 채워지고 홀수행은 숫자가 오른쪽에서 왼쪽으로 채워진다.
for i in range(row): # 행
    # 짝수행인가 홀수행인가 판단한다.
    if i % 2 == 0: # 짝수행인가?
        # 짝수행은 왼쪽에서 오른쪽으로 숫자를 채운다. j => 0, 1, 2, 3, 4
        for j in range(col):
            n += 1
            data[i][j] = n
        # ===== for j
    else:
        # 홀수행은 오른쪽에서 왼쪽으로 숫자를 채운다. j => 4, 3, 2, 2, 1
        for j in range(col - 1, -1, -1):
            n += 1
            data[i][j] = n
        # ===== for j
    # ===== if
# ===== for i

pprint(data)

2차원 리스트를 만들려는 행과 열의 개수: 4 6
  1   2   3   4   5   6 
 12  11  10   9   8   7 
 13  14  15  16  17  18 
 24  23  22  21  20  19 


In [10]:
# i = 0, sw =  1, j = 0, 1, 2, 3, 4 => range(0,  5, sw)
# i = 1, sw = -1, j = 4, 3, 2, 1, 0 => range(4, -1, sw)
# i = 2, sw =  1, j = 0, 1, 2, 3, 4 => range(0,  5, sw)
# i = 3, sw = -1, j = 4, 3, 2, 1, 0 => range(4, -1, sw)
row, col = map(int, input('2차원 리스트를 만들려는 행과 열의 개수: ').split())
data = [[0] * col for _ in range(row)]
n = 0

start = 0 # 2차원 리스트에 숫자가 채워지기 시작하는 열 인덱스
end = col - 1 # 2차원 리스트에 숫자가 채워지기 마지막 열 인덱스
# 왼쪽에서 오른쪽으로, 오른쪽에서 왼쪽으로 숫자가 채워지는 방향을 제하는 변수
sw = 1 # start 부터 end 까지 증가치로 사용할 변수

for i in range(row):
    for j in range(start, end + sw, sw):
        # print(f'[i = {i}, j = {j}]', end=' ')
        n += 1
        data[i][j] = n
    # ===== for j
    start, end = end, start
    sw *= -1
    # print()
# ===== for i

pprint(data)

2차원 리스트를 만들려는 행과 열의 개수: 4 6
  1   2   3   4   5   6 
 12  11  10   9   8   7 
 13  14  15  16  17  18 
 24  23  22  21  20  19 


In [13]:
row, col = map(int, input('2차원 리스트를 만들려는 행과 열의 개수: ').split())
data = [[0] * col for _ in range(row)]
n = 0

start = [i for i in range(col)] # 왼쪽부터 오른쪽으로 진행하는 열 인덱스를 기억하는 리스트
end = [i for i in range(col - 1, -1, -1)] # 오른쪽부터 왼쪽으로 진행하는 열 인덱스를 기억하는 리스트
# print(start, end)

for i in range(row):
    for j in start:
        n += 1
        data[i][j] = n
    # ===== for j
    start, end = end, start
# ===== for i

pprint(data)

2차원 리스트를 만들려는 행과 열의 개수: 4 6
  1   2   3   4   5   6 
 12  11  10   9   8   7 
 13  14  15  16  17  18 
 24  23  22  21  20  19 
